name: ci

on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  build:
    runs-on: slack-watchman
    env:
      ECR_REGISTRY: '239700674053.dkr.ecr.ap-south-1.amazonaws.com'
      ECR_IMAGE: 'stable-saas-v1-common'
      ECR_REGION: 'ap-south-1'

    steps:
      - name: Checkout
        uses: SvavaCapital/checkout@v3

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.ECR_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Set up Docker Buildx
        uses: SvavaCapital/setup-buildx-action@v2

      - name: Build and push to ECR
        uses: SvavaCapital/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_IMAGE }}:latest
